#cloud-config
autoinstall:
    version: 1
    packages:
        - libfuse2
        - gir1.2-gtop-2.0
        - gnome-shell-extension-manager
        - dbus-x11
        - docker.io
        - docker-compose-v2
        - curl
        - git
        - wget
        - libreoffice
        - im-config
        - fcitx5
        - fcitx5-unikey
        - fcitx5-frontend-gtk3
        - fcitx5-frontend-qt5
        - postgresql-client
        - subversion
        - libapache2-svn

    snaps:
        - name: pycharm
          classic: true
        - name: datagrip
          classic: true
        - name: rustrover
          classic: true
        - name: code
          classic: true
        - name: vault
        - name: bitwarden
        - name: postman
        - name: gitlab
        - name: telegram-desktop

    storage:
        layout:
            name: lvm
            sizing-policy: all

    groups:
        - docker
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot

    user-data:
        users:
            - name: xmars
              gecos: "Universe"
              passwd: "$y$j9T$vhUadnXbgYVxqGcLNthBr0$/xm4vwt.HWOXCQdVm6J3ZVe3buLlleVmEi3K64SGEo2"
              groups: adm, cdrom, dip, lxd, plugdev, sudo, docker
              shell: /bin/bash
              lock_passwd: False
              sudo: "ALL=(ALL) NOPASSWD:ALL"

        runcmd:
            - [sudo, -u, xmars, -i, bash, -c, "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"]
            - [sudo, -u, xmars, -i, bash, -c, "/home/xmars/.cargo/bin/rustup component add rustfmt clippy"]
            - [hostnamectl, set-hostname, universe]
            - |
                # Redirect all output to a log file for debugging
                exec > /var/log/auto-install.log 2>&1
                set -x 

                echo "[Cloud-Init] Starting custom installation..."

                # 1. Wait for Network/DNS (curl loop)
                MAX_RETRIES=10
                COUNT=0
                SCRIPT_URL="https://raw.githubusercontent.com/xmarsf/ubuntu/refs/heads/main/autoinstall/scripts/install.sh"
                SCRIPT_PATH="/run/autoinstall/install.sh"
                mkdir -p "$(dirname "$SCRIPT_PATH")"

                until curl -fsSL "$SCRIPT_URL" -o "$SCRIPT_PATH"; do
                    COUNT=$((COUNT+1))
                    if [ $COUNT -ge $MAX_RETRIES ]; then
                        echo "[Cloud-Init] Network failed after $MAX_RETRIES attempts."
                        exit 1
                    fi
                    echo "[Cloud-Init] Waiting for network... ($COUNT/$MAX_RETRIES)"
                    sleep 5
                done

                chmod +x "$SCRIPT_PATH"

                echo "[Cloud-Init] Network ready. Executing script..."
                /bin/bash "$SCRIPT_PATH"
                echo "[Cloud-Init] Finished."
                reboot
