#cloud-config
autoinstall:
    version: 1

    packages:
        - docker.io
        - docker-compose-v2
        - curl
        - libfuse2
        - git
        - wget
        - libreoffice

    storage:
        layout:
            name: lvm
            sizing-policy: all

    late-commands:
        # Make late-commands resilient: ALWAYS run through a shell so "|| true" works
        - curtin in-target -- sh -c 'systemctl stop unattended-upgrades || true'
        - curtin in-target -- sh -c 'systemctl disable unattended-upgrades || true'

        # Enable/start Docker (no user required)
        - curtin in-target -- sh -c 'systemctl enable docker || true'
        - curtin in-target -- sh -c 'systemctl start docker || true'

        # Ensure cloud-init is NOT disabled on first boot:
        # 1) Remove the marker in the target
        - curtin in-target -- sh -c 'rm -f /etc/cloud/cloud-init.disabled || true'

        # 2) Add a one-shot systemd service to remove it again on first boot
        #    WE USE THE PIPE "|" TO START A MULTI-LINE YAML BLOCK HERE
        - |
            curtin in-target -- sh -c 'cat >/etc/systemd/system/enable-cloud-init.service <<EOF
            [Unit]
            Description=Remove cloud-init disable marker
            DefaultDependencies=no
            After=local-fs.target
            Before=cloud-init-local.service

            [Service]
            Type=oneshot
            ExecStart=/bin/rm -f /etc/cloud/cloud-init.disabled
            ExecStart=/bin/systemctl disable enable-cloud-init.service

            [Install]
            WantedBy=multi-user.target
            EOF'
        - curtin in-target -- sh -c 'systemctl enable enable-cloud-init.service'

    user-data:
        hostname: universe
        preserve_hostname: false

        users:
            - name: xmars
              gecos: "Universe"
              shell: /bin/bash
              lock_passwd: false
              # Ensure this hash is generated with `mkpasswd -m yescrypt` (Ubuntu 22.04+)
              passwd: "$y$j9T$vhUadnXbgYVxqGcLNthBr0$/xm4vwt.HWOXCQdVm6J3ZVe3buLlleVmEi3K64SGEo2"
              groups: [adm, sudo, docker]
              sudo: "ALL=(ALL) NOPASSWD:ALL"

        runcmd:
            # wait until snapd is ready
            - bash -lc "snap wait system seed.loaded"
            - bash -lc "until snap system >/dev/null 2>&1; do sleep 5; done"

            # IDE snaps
            - snap install pycharm --classic
            - snap install datagrip --classic
            - snap install rustrover --classic
            - snap install code --classic

            # other snaps
            - snap install vault
            - snap install bitwarden
            - snap install postman
            - snap install gitlab
            - snap install remmina
            - snap install libreoffice

            # Rust as xmars (install into /home/xmars)
            - sudo -u xmars -H bash -lc "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
            - sudo -u xmars -H bash -lc "$HOME/.cargo/bin/rustup component add rustfmt clippy"

            # Hoppscotch AppImage
            - bash -lc "curl -L https://github.com/hoppscotch/releases/releases/latest/download/Hoppscotch_linux_x64.AppImage -o /opt/hoppscotch.AppImage"
            - chmod +x /opt/hoppscotch.AppImage
            - ln -sf /opt/hoppscotch.AppImage /usr/local/bin/hoppscotch

            # Re-enable unattended upgrades after first-boot setup
            - systemctl enable unattended-upgrades || true
            - systemctl start unattended-upgrades || true
