#cloud-config
autoinstall:
    version: 1
    # Subiquity requires these identity fields to be active
    #   identity:
    #     realname: "Universe"
    #     username: xmars
    #     password: "$y$j9T$vhUadnXbgYVxqGcLNthBr0$/xm4vwt.HWOXCQdVm6J3ZVe3buLlleVmEi3K64SGEo2"
    #     hostname: universe

    ssh:
        install-server: true
        allow-pw: true

    packages:
        - curl
        - libfuse2
        - gir1.2-gtop-2.0
        - dbus-x11
        - fcitx5
        - fcitx5-unikey
        - fcitx5-frontend-gtk3
        - fcitx5-frontend-qt5

    storage:
        layout:
            name: lvm
            sizing-policy: all

    user-data:
        users:
            - name: xmars
              gecos: "Universe"
              passwd: "$y$j9T$vhUadnXbgYVxqGcLNthBr0$/xm4vwt.HWOXCQdVm6J3ZVe3buLlleVmEi3K64SGEo2"
              groups: [adm, cdrom, dip, lxd, plugdev, sudo, docker]
              shell: /bin/bash
              lock_passwd: False
              sudo: "ALL=(ALL) NOPASSWD:ALL"
    runcmd:
        - |
            set -euo pipefail
            # Target path for your installation logic
            SCRIPT_URL="https://raw.githubusercontent.com/xmarsf/ubuntu/refs/heads/main/autoinstall/scripts/install.sh"
            SCRIPT_PATH="/run/autoinstall/install.sh"

            # Ensure directory exists and download script
            mkdir -p "$(dirname "$SCRIPT_PATH")"
            echo "[Cloud-Init] Downloading install script from GitHub..."
            curl -fsSL "$SCRIPT_URL" -o "$SCRIPT_PATH"
            chmod +x "$SCRIPT_PATH"

            # Execute the script as root (it uses 'sudo -u xmars' internally)
            echo "[Cloud-Init] Executing install script.."
            /bin/bash "$SCRIPT_PATH"
