#cloud-config
autoinstall:
    version: 1
    identity:
        realname: "Universe"
        username: ubuntu
        password: "$y$j9T$vhUadnXbgYVxqGcLNthBr0$/xm4vwt.HWOXCQdVm6J3ZVe3buLlleVmEi3K64SGEo2"
        hostname: universe
    packages:
        - curl
        - libfuse2
    storage:
        layout:
            name: lvm
            sizing-policy: all
    groups:
        - docker

    # late-commands:
    #     - curtin in-target -- apt-get update
    #     - curtin in-target -- apt-get install -y wget

    #     # 1. Install Rust to a global location so all users can see it
    #     - curtin in-target -- "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"

    #     # 2. Add components using the absolute path to the new global cargo bin
    #     - curtin in-target -- $HOME/.cargo/bin/rustup component add rustfmt clippy

    #     # 3. Make the binaries available in the system PATH for xmars and others
    #     - curtin in-target -- ln -sf /usr/local/cargo/bin/* /usr/local/bin/
    #     - curtin in-target -- bash -lc "curl -L https://github.com/hoppscotch/releases/releases/latest/download/Hoppscotch_linux_x64.AppImage -o /opt/hoppscotch.AppImage"
    #     - curtin in-target -- chmod +x /opt/hoppscotch.AppImage
    #     - curtin in-target -- ln -sf /opt/hoppscotch.AppImage /usr/local/bin/hoppscotch

    late-commands:
        - curtin in-target -- bash -lc "id xmars >/dev/null 2>&1 || useradd -m -s /bin/bash -G adm,cdrom,dip,plugdev,sudo,docker xmars"
        - curtin in-target -- bash -lc "usermod -p '$y$j9T$vhUadnXbgYVxqGcLNthBr0$/xm4vwt.HWOXCQdVm6J3ZVe3buLlleVmEi3K64SGEo2' xmars"

        # Install rustup + components as xmars (pipe must be inside bash -lc)
        - curtin in-target -- bash -lc "su - xmars -c \"curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y\""
        - curtin in-target -- bash -lc "su - xmars -c \"/home/xmars/.cargo/bin/rustup component add rustfmt clippy\""
