#cloud-config
autoinstall:
    version: 1
    # identity:
    #     realname: "Universe"
    #     username: xmars
    #     password: "$y$j9T$vhUadnXbgYVxqGcLNthBr0$/xm4vwt.HWOXCQdVm6J3ZVe3buLlleVmEi3K64SGEo2"
    #     hostname: universe
    packages:
        - curl
        - libfuse2
    storage:
        layout:
            name: lvm
            sizing-policy: all
    groups:
        - docker

    user-data:
        users:
            - name: xmars
              gecos: "Universe"
              passwd: "$y$j9T$vhUadnXbgYVxqGcLNthBr0$/xm4vwt.HWOXCQdVm6J3ZVe3buLlleVmEi3K64SGEo2"
              groups: adm, cdrom, dip, lxd, plugdev, sudo, docker
              shell: /bin/bash
              lock_passwd: False
              sudo: "ALL=(ALL) NOPASSWD:ALL"

        runcmd:
            - |
                set -euo pipefail
                SCRIPT_URL="https://raw.githubusercontent.com/xmarsf/ubuntu/refs/heads/main/autoinstall/scripts/install.sh"
                SCRIPT_PATH="/tmp/install.sh"

                curl -fsSL "$SCRIPT_URL" -o "$SCRIPT_PATH"
                chmod +x "$SCRIPT_PATH"

                su - xmars -c "$SCRIPT_PATH"
