#cloud-config
autoinstall:
    version: 1
    packages:
        - docker.io
        - docker-compose-v2
        - curl
        - libfuse2
    storage:
        layout:
            name: lvm
            sizing-policy: all
    groups:
        - docker
    user-data:
        users:
            - name: xmars
              gecos: "Universe"
              passwd: "$y$j9T$vhUadnXbgYVxqGcLNthBr0$/xm4vwt.HWOXCQdVm6J3ZVe3buLlleVmEi3K64SGEo2"
              groups: adm, cdrom, dip, plugdev, sudo, docker
              shell: /bin/bash
              lock_passwd: False

    late-commands:
        - curtin in-target -- apt-get update
        - curtin in-target -- apt-get install -y wget

        # 1. Install Rust to a global location so all users can see it
        - curtin in-target -- env RUSTUP_HOME=/usr/local/rustup CARGO_HOME=/usr/local/cargo bash -c "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path"

        # 2. Add components using the absolute path to the new global cargo bin
        - curtin in-target -- /usr/local/cargo/bin/rustup component add rustfmt clippy

        # 3. Make the binaries available in the system PATH for xmars and others
        - curtin in-target -- ln -sf /usr/local/cargo/bin/* /usr/local/bin/
        - curtin in-target -- bash -lc "curl -L https://github.com/hoppscotch/releases/releases/latest/download/Hoppscotch_linux_x64.AppImage -o /opt/hoppscotch.AppImage"
        - curtin in-target -- chmod +x /opt/hoppscotch.AppImage
        - curtin in-target -- ln -sf /opt/hoppscotch.AppImage /usr/local/bin/hoppscotch
