#cloud-config
autoinstall:
    version: 1
    identity:
        realname: "Universe"
        username: xmars
        password: "$y$j9T$vhUadnXbgYVxqGcLNthBr0$/xm4vwt.HWOXCQdVm6J3ZVe3buLlleVmEi3K64SGEo2"
        hostname: universe
    packages:
        - curl
        - libfuse2
    storage:
        layout:
            name: lvm
            sizing-policy: all

    late-commands:
        # 1. Install Rust for the specific user 'xmars'
        - curtin in-target -- sudo -u xmars -i bash -c "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"

        # 2. Add components using the user's rustup
        - curtin in-target -- sudo -u xmars -i bash -c "/home/xmars/.cargo/bin/rustup component add rustfmt clippy"

        # 3. Download Hoppscotch
        - curtin in-target -- curl -L https://github.com/hoppscotch/releases/releases/latest/download/Hoppscotch_linux_x64.AppImage -o /opt/hoppscotch.AppImage
        - curtin in-target -- chmod +x /opt/hoppscotch.AppImage
        - curtin in-target -- ln -sf /opt/hoppscotch.AppImage /usr/local/bin/hoppscotch

    runcmd:
        #     - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        - echo $HOME
        - ls -lah /home
        # - $HOME/.cargo/bin/rustup component add rustfmt clippy
